# Generated by Django 5.2.8 on 2025-11-15 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=500, verbose_name='Tam Adres')),
                ('street', models.CharField(max_length=255, verbose_name='Sokak/Cadde')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Posta Kodu')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Müşteri Adresi',
                'verbose_name_plural': 'Müşteri Adresleri',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
