# Generated by Django 5.2.8 on 2025-11-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Firma Adı')),
                ('slug', models.SlugField(help_text='URL için küçük harf ve tire ile ayrılmış isim', unique=True)),
                ('description', models.TextField(verbose_name='Hizmet Açıklaması')),
                ('location_text', models.CharField(max_length=255, verbose_name='Adres / Konum')),
                ('encrypted_sensitive_data', models.TextField(blank=True, null=True, verbose_name='Şifreli Hassas Veri')),
            ],
            options={
                'verbose_name': 'Firma/İşletme',
                'verbose_name_plural': 'Firmalar/İşletmeler',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Hizmet Başlığı')),
                ('description', models.TextField(verbose_name='Hizmet Detayı')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Arama Anahtar Kelimeleri (Virgülle Ayrılmış)')),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min. Fiyat')),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max. Fiyat')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.company')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Müşteri E-Postası')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('timeout', 'Zaman Aşımı')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_commission_due', models.BooleanField(default=False, verbose_name='Komisyon Kaydı Oluşturuldu mu?')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, verbose_name='Kesilen Komisyon Tutarı')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='core.company')),
                ('requested_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service', verbose_name='Talep Edilen Hizmet')),
            ],
            options={
                'verbose_name': 'Yönlendirme Talebi',
                'verbose_name_plural': 'Yönlendirme Talepleri',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Müşteri'), ('seller', 'Firma/Satıcı'), ('admin', 'Yönetici')], default='customer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
