# Generated by Django 5.2.8 on 2025-11-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'seller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
    ]
