# Generated by Django 5.2.8 on 2025-11-15 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Kapak Fotoğrafı URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Varsayılan Teslimat Ücreti'),
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_areas',
            field=models.JSONField(blank=True, null=True, verbose_name='Teslimat Bölgeleri (GeoJSON)'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta'),
        ),
        migrations.AddField(
            model_name='company',
            name='estimated_delivery_time_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tahmini Teslimat Süresi (dk)'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Logo URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Sipariş Tutarı'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='company',
            name='special_days',
            field=models.JSONField(blank=True, null=True, verbose_name='Özel Gün Saatleri'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi No'),
        ),
        migrations.AddField(
            model_name='company',
            name='trade_registry_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticaret Sicil No'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours',
            field=models.JSONField(blank=True, null=True, verbose_name='Çalışma Saatleri'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.category'),
        ),
    ]
