"""
Django settings for ServiceRadar project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# settings.py dosyasında SECRET_KEY satırını bulun

import os
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-key-for-development-do-not-use-in-production') 
# Not: Gerçek hayatta bu değeri bir .env dosyasından çekmeliyiz.

FERNET_KEY = os.environ.get(
    'FERNET_KEY', 
    'rX2q1N1s574r61MO9tdQk_lsFlbqBZwbqWEkyWbOTfQ='
)



# SECURITY WARNING: don't run with debug turned on in production!


DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # my apps
    'core',
    
    # 3rd party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Google OAuth için
    'rest_framework', # DRF'nin kurulu olmadığı bir ortamda JWT kullanmak için
    'haystack',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'ServiceRadar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ServiceRadar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ServiceRadar/settings.py
# ...

# Allauth ayarları
AUTHENTICATION_BACKENDS = (
    # Gerekli: Django Admin için varsayılan kimlik doğrulama
    'django.contrib.auth.backends.ModelBackend',
    # 'allauth' ile Google dahil sosyal medya girişi
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Login/Logout yönlendirmeleri
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Google OAuth için Site Framework zorunlu
SITE_ID = 1

# Kullanıcı adı gerektirmeme (email ile giriş)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'



# ServiceRadar/settings.py
# ... (En sona veya uygun bir yere ekleyin)

# Haystack Arama Motoru Ayarları
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        # Arama indekslerinin tutulacağı dizin. Proje kökünde oluşturulacak.
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'), 
    },
}

# Arama sonuçlarının kaç tanesinin tek bir sayfada gösterileceği. (Opsiyonel)
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 20

# Veritabanına her kayıt/güncelleme yapıldığında indeksi otomatik güncelleyecek.
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'


# ServiceRadar/settings.py
# ...

Q_CLUSTER = {
    'name': 'ServiceRadarCluster',
    'workers': 4, 
    'timeout': 60,   # Maksimum görev süresi 60 saniye (Önceki 90'dı)
    'retry': 120,    # Hata durumunda 120 saniye (2 dakika) sonra tekrar dene
    'queue_limit': 50,
    'orm': 'default',
    
    # Periyodik Görevler (Schedule)
    'schedule': [
        {
            'name': 'check_referral_timeout',
            'func': 'core.tasks.check_referral_timeout', # Hangi fonksiyon çalışacak
            'minutes': 30, # Her 30 dakikada bir çalıştır (Test için sık aralık)
            'repeats': -1, # Sürekli tekrar et
            'hook': 'core.tasks.log_completion', # Opsiyonel: Görev bitince ne yapsın
        },
        # Ekstra: Haftalık raporlama için taslak
        # {
        #     'name': 'weekly_commission_report',
        #     'func': 'core.tasks.generate_weekly_commission_report',
        #     'schedule_type': 'W', # Haftalık
        #     'repeats': -1,
        #     'next_run': timezone.now() + timedelta(days=7), # Bir hafta sonra başla
        # },
    ]
}