"""
Django settings for ServiceRadar project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from datetime import timedelta # JWT için timedelta import edildi

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-key-for-development-do-not-use-in-production') 
# Not: Gerçek hayatta bu değeri bir .env dosyasından çekmeliyiz.

FERNET_KEY = os.environ.get(
    'FERNET_KEY', 
    'rX2q1N1s574r61MO9tdQk_lsFlbqBZwbqWEkyWbOTfQ='
)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# =======================================================
# UYGULAMA TANIMLAMALARI (INSTALLED_APPS)
# =======================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 3rd party apps (Yetkilendirme, CORS, Arama, Async)
    'rest_framework',        # Django Rest Framework (JWT altyapısı için)
    'corsheaders',           # React CORS desteği için
    'haystack',              # Arama motoru
    'django_q',              # Async tasks
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Google OAuth için
    
    # my apps
    'core',
    'firm',
    'users',
]

# =======================================================
# MIDDLEWARE TANIMLAMALARI
# =======================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CORS Middleware'ı SecurityMiddleware'den hemen sonra olmalı
    'corsheaders.middleware.CorsMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'ServiceRadar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ServiceRadar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =======================================================
# ALLAUTH AYARLARI
# =======================================================

AUTHENTICATION_BACKENDS = (
    # Gerekli: Django Admin için varsayılan kimlik doğrulama
    'django.contrib.auth.backends.ModelBackend',
    # 'allauth' ile Google dahil sosyal medya girişi
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Login/Logout yönlendirmeleri
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Google OAuth için Site Framework zorunlu
SITE_ID = 1

# Kullanıcı adı gerektirmeme (email ile giriş)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'


# =======================================================
# JWT (JSON WEB TOKEN) & DRF AYARLARI
# =======================================================

REST_FRAMEWORK = {
    # Varsayılan yetkilendirme sınıfı olarak JWT'yi ayarlayın
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # İzin kontrolünü ayarlar (Genellikle sadece yetkili kullanıcıya izin ver)
    # Bu ayar, NinjaAPI kullanıldığı için sadece DRF endpoint'lerini etkiler.
    # Ninja'da Yetkilendirmeyi elle ayarlayacağız.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

SIMPLE_JWT = {
    # Erişim token'ının geçerlilik süresi (örneğin 60 dakika)
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60), 
    # Yenileme token'ının geçerlilik süresi (örneğin 1 gün)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Token başlığını değiştirme imkanı
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# =======================================================
# CORS AYARLARI (React Frontend ile Bağlantı İçin)
# =======================================================

# Geliştirme ortamında belirli bir adrese izin veriyoruz
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Vite varsayılan portu
    "http://127.0.0.1:5173",
    "http://localhost:3000", # Create-React-App varsayılan portu
]

# Eğer tarayıcıda Cookieleri veya Yetkilendirme başlıklarını kullanacaksak:
CORS_ALLOW_CREDENTIALS = True


# =======================================================
# HAYSTACK (Arama Motoru) AYARLARI
# =======================================================

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        # Arama indekslerinin tutulacağı dizin. Proje kökünde oluşturulacak.
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'), 
    },
}

# Arama sonuçlarının kaç tanesinin tek bir sayfada gösterileceği. (Opsiyonel)
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 20

# Veritabanına her kayıt/güncelleme yapıldığında indeksi otomatik güncelleyecek.
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'


# =======================================================
# DJANGO-Q (ASENKRON GÖREVLER) AYARLARI
# =======================================================

Q_CLUSTER = {
    'name': 'ServiceRadarCluster',
    'workers': 4, 
    'timeout': 60,  # Maksimum görev süresi 60 saniye
    'retry': 120, # Hata durumunda 120 saniye (2 dakika) sonra tekrar dene
    'queue_limit': 50,
    'orm': 'default',
    
    # Periyodik Görevler (Schedule)
    'schedule': [
        {
            'name': 'check_referral_timeout',
            'func': 'core.tasks.check_referral_timeout', # Hangi fonksiyon çalışacak
            'minutes': 30, # Her 30 dakikada bir çalıştır
            'repeats': -1, # Sürekli tekrar et
            'hook': 'core.tasks.log_completion', # Opsiyonel: Görev bitince ne yapsın
        },
        # Ekstra: Haftalık raporlama için taslak
        # {
        #     'name': 'weekly_commission_report',
        #     'func': 'core.tasks.generate_weekly_commission_report',
        #     'schedule_type': 'W', # Haftalık
        #     'repeats': -1,
        #     'next_run': timezone.now() + timedelta(days=7), 
        # },
    ]
}
AUTH_USER_MODEL = 'users.User'